version: '3'

services:

  # For running the Flask server
  web:
    build: .
    env_file: .env
    environment:
      KB_SERVICE_TOKEN: ${KB_SERVICE_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  # For running the file server
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - data:/data
    command: server /data

  # The minio cli interface
  mc:
    image: minio/mc
    volumes:
      - data:/data

volumes:
  data:
