version: '3'

services:

  # For running the Flask server
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-python
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
