version: '3'

services:

  # For running the Flask server
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-python
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  # For running the file server
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - data:/data
    command: server /data

volumes:
  data:
